-- ========================================
-- 解决 pngrd 用户访问 PNGDEV 表的问题
-- ========================================

-- 方案1：用 pngdev 用户执行（或者 DBA 用户）
-- 授权 pngrd 可以查询 PNGDEV 的表
GRANT SELECT ON PNGDEV.BACKEND_ADMIN TO pngrd;
GRANT SELECT ON PNGDEV.BACKEND_ADMIN_ROLE TO pngrd;
COMMIT;

-- 方案2：切换到 pngrd 用户，创建同义词
-- 这样代码里直接用 BACKEND_ADMIN 就能访问到 PNGDEV.BACKEND_ADMIN
CREATE SYNONYM BACKEND_ADMIN FOR PNGDEV.BACKEND_ADMIN;
CREATE SYNONYM BACKEND_ADMIN_ROLE FOR PNGDEV.BACKEND_ADMIN_ROLE;

-- 验证同义词是否创建成功
SELECT SYNONYM_NAME, TABLE_OWNER, TABLE_NAME
FROM USER_SYNONYMS
WHERE SYNONYM_NAME IN ('BACKEND_ADMIN', 'BACKEND_ADMIN_ROLE');

-- 测试查询
SELECT USERNAME, STATUS FROM BACKEND_ADMIN WHERE STATUS='active';
