SELECT USERNAME, PASSWORD, STATUS FROM BACKEND_ADMIN WHERE STATUS='active';


-- 查询所有激活状态的后台管理员用户
SELECT * FROM BACKEND_ADMIN WHERE STATUS = 'active';

-- 查询特定用户名
SELECT * FROM PNGDEV.BACKEND_ADMIN WHERE USERNAME = 'admin' AND STATUS = 'active';

-- 查询用户及其角色信息（关联角色表）
SELECT 
    a.USERNAME,
    a.STATUS,
    a.CREATE_DATE,
    r.ROLENAME,
    r.PRIVILEGE,
    r.RESOURCE
FROM PNGDEV.BACKEND_ADMIN a
LEFT JOIN PNGDEV.BACKEND_ADMIN_ROLE r ON a.ROLE_IDN = r.IDN
WHERE a.STATUS = 'active';

-- 验证特定用户的密码（MD5）
SELECT USERNAME, PASSWORD, STATUS, ROLE_IDN 
FROM PNGDEV.BACKEND_ADMIN 
WHERE USERNAME = 'admin' 
AND PASSWORD = '0192023a7bbd73250516f069df18b500'  -- admin123 的 MD5
AND STATUS = 'active';