https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getUser
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getMyPraiseCount
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getUser
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getUser
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getMyPraiseCount
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getUser
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getMyPraiseCount
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getUser
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getMyPraiseCount
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getMyPraiseCount
https://pt777aiguo.mypengyouquan.com/api/friend/user/1.0/getMyPraiseCount
https://pt777aiguo.mypengyouquan.com/api/friend/levelSetting/1.0/getLevel
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findPersonalInfoPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMonthlyRankingPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMonthlyRankingPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMonthlyRankingFirstList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMatchPreferredPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMonthlyRankingPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findPersonalInfoPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMasterDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findProgrammePreferredEntity
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findPlanDetailed
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findPersonalInfoPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findPersonalInfoPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMyAttentionPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findProgrammePreferredPageList
https://pt777aiguo.mypengyouquan.com/api/friend/pushOrder/external/1.0/findMyPurchasePageList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/1.0/getCountList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/1.0/getCountList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/1.0/getCountList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/1.0/getCountList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/1.0/getCountList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/1.0/getCountList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/2.0/pageList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/2.0/pageList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/2.0/pageList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/2.0/pageList
https://pt777aiguo.mypengyouquan.com/api/friend/circle/2.0/pageList
https://pt777aiguo.mypengyouquan.com/api/friend/task/1.0/queryTasks